apiVersion: v1
kind: ConfigMap
metadata:
  name: otterscan
  namespace: otterscan
  labels:
    app.kubernetes.io/name: otterscan
data:
  config.json: |
    {
      "connections": [
        {
          "menuName": "zq2-protomainnet",
          "url": "https://api.zq2-protomainnet.zilliqa.com",
          "hostnames": ["explorer.zq2-protomainnet.zilliqa.com"]
        }
      ]
    }
