apiVersion: v1
kind: ConfigMap
metadata:
  name: otterscan
  namespace: otterscan
  labels:
    app.kubernetes.io/name: otterscan
data:
  config.json: |
    {
      "connections": [
        {
          "menuName": "zq2-prototestnet",
          "url": "https://api.zq2-prototestnet.zilliqa.com",
          "hostnames": ["explorer.zq2-prototestnet.zilliqa.com"]
        },
        {
          "menuName": "zq2-devnet",
          "url": "https://api.zq2-devnet.zilliqa.com",
          "hostnames": ["explorer.zq2-devnet.zilliqa.com"]
        },
        {
          "menuName": "zq1-testnet",
          "url": "https://testnet-v932-fireblocks.testnet-ase1.zq1.dev",
          "hostnames": ["otterscan.testnet.zilliqa.com"]
        },
        {
          "menuName": "zq1-devnet",
          "url": "https://devnet-pub-v930-otterscan.devnet-ase1.zq1.dev",
          "hostnames": ["otterscan.devnet.zilliqa.com"]
        }
      ]
    }
