apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: otterscan
  namespace: otterscan
  labels:
    app.kubernetes.io/name: otterscan
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: RESPONSE_CODE
