apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - certificate.yaml

patches:
  - target:
      kind: Deployment
      name: developer-portal
    patch: |-
      - op: replace
        path: "/spec/template/spec/containers/0/image"
        value:  asia-docker.pkg.dev/prj-d-dev-apps-n3p4o97j/zilliqa/developer-portal:latest
  - target:
      kind: Ingress
      name: developer-portal
    patch: |-
      - op: replace
        path: "/spec/rules/0/host"
        value: developer-portal.zildev.dev
      - op: replace
        path: "/spec/rules/1/host"
        value: dev-dev.zilliqa.com
      - op: replace
        path: /metadata/annotations
        value:
          kubernetes.io/ingress.class: gce
          kubernetes.io/ingress.global-static-ip-name: developer-portal-zildev-dev
          networking.gke.io/managed-certificates: developer-portal

namespace: developer-portal-dev
