apiVersion: v1
kind: ConfigMap
metadata:
  name: otterscan
  namespace: otterscan
  labels:
    app.kubernetes.io/name: otterscan
data:
  config.json: |
    {
      "connections": [
        {
          "menuName": "zq2-mainnet",
          "url": "https://api.zilliqa.com",
          "hostnames": ["explorer.zq2-mainnet.zilliqa.com"]
        },
        {
          "menuName": "zq2-testnet",
          "url": "https://api.testnet.zilliqa.com",
          "hostnames": ["explorer.zq2-testnet.zilliqa.com"]
        },
        {
          "menuName": "zq2-devnet",
          "url": "https://api.zq2-devnet.zilliqa.com",
          "hostnames": ["explorer.zq2-devnet.zilliqa.com"]
        },
        {
          "menuName": "zq2-infratest",
          "url": "https://api.zq2-infratest.zilstg.dev",
          "hostnames": ["explorer.zq2-infratest.zilstg.dev"]
        }
      ]
    }
