apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: otterscan-dev

resources:
  - ../../base
  - configmap.yaml
  - httproute.yaml

patches:
  - target:
      kind: Deployment
      name: otterscan
    patch: |-
      - op: add
        path: /spec/template/spec/volumes
        value:
          - name: network-config
            configMap:
              name: otterscan
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts
        value:
          - mountPath: /usr/share/nginx/html/config.json
            readOnly: true
            name: network-config
            subPath: config.json
