apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: otterscan
  namespace: otterscan
  labels:
    app.kubernetes.io/name: "otterscan"
spec:
  timeoutSec: 120
  healthCheck:
    requestPath: /health
