apiVersion: apps/v1
kind: Deployment
metadata:
  name: otterscan
  namespace: otterscan
  labels:
    app.kubernetes.io/name: otterscan
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: otterscan
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otterscan
    spec:
      containers:
        - image: otterscan
          name: otterscan
          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 100Mi
          ports:
            - containerPort: 80
          env:
            - name: DISABLE_CONFIG_OVERWRITE
              value: "disable"
          readinessProbe:
            httpGet:
              path: /
              port: 80
