name: Check main PR source branch
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  check-pr-source:
    runs-on: ubuntu-latest
    steps:
      - name: Verify source branch
        if: github.base_ref == 'main' && github.head_ref != 'develop'
        run: |
          echo "Error: Pull request source branch is not 'develop'."
          exit 1
